@startuml
skinparam actorStyle awesome
"Гість" as Guest
"Користувач" as User
"Адміністратор" as Admin
Guest -left-> (g_01)
Guest -right-> (g_02)
Guest -up-> (g_03)
User -right-> (u_01)
User -left-> (u_02)
User -left-> (u_03)
User -right-> (u_04)
User -up-> (u_05)
Admin -left-> (a_01)
Admin -up-> (a_02)
Admin -left-> (a_03)
Admin -down-> (a_04)
Admin -up-> (a_05)
Admin -down-> (a_06)
(g_02) .> (a_01) : наступне
(u_01) .> (a_02) : наступне
(u_04) .> (a_03) : наступне
(a_03) .> (a_04) : наступне
(u_05) <.> (a_05) : взаємна комунікація
Admin -up-|> User
User -up-|> Guest

'Guest 
"Aвторизація існуючого користувача" as (g_01)
"Реєстрація облікового запису" as (g_02)
"Перегляд основних даних" as (g_03)

'User
"Редагування своїх даних" as (u_01)
"Пошук інших користувачів" as (u_02)
"Пошук вакантних місць" as (u_03)
"Cтворення запиту на реєстрацію нової установи" as (u_04)
"Зв'язок з техпідтримкою" as (u_05)

'Admin
"Реєстрація користувачів" as (a_01)
"Внесення змін до даних користувачів" as (a_02)
"Обробка запитів на реєстрацію установи" as (a_03)
"Реєстрація установ" as (a_04)
"Зв'язок з користувачами" as (a_05)
"Редагування інформації про об'єкт інфраструктури" as (a_06)
@enduml
